### ISSUE TITLE
Add GAE example

### ISSUE THREAD

**Issue by JustinBeckwith** [JustinBeckwith/go-yelp#11]
Mainly to verify that the library will work on GAE

**Comment by headslow22** [comment]
The package will not work on App Engine because the application cannot specify the *http.Client to use.

I suggest adding a *http.Client field to client:

    type Client struct {
	Options AuthOptions
        HTTPClient *http.Client
    }

and a function to get the field or a default value if the field is nil:

   func (client *Client) httpClient() {
         if client.HTTPClient == nil {
              return http.DefaultClient
        }
        return client.HTTPClient
  }

Use client.httpClient() instead of http.DefaultClient when issuing HTTP requests.

**Comment by JustinBeckwith** [comment]
done
